server:
  port: 10010
  servlet:
    context-path: ${SERVICE_PATH:/hungnm/best-practices/redis}
spring:
  cache:
    redis:
      time-to-live: 1D
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: ${REDIS_TIMEOUT:500ms}
    client-type: jedis

